# Project: cal
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o scan.o print.o
LINKOBJ  = main.o scan.o print.o
LIBS     = -L"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib" -L"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Calculator.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

scan.o: scan.cpp
	$(CPP) -c scan.cpp -o scan.o $(CXXFLAGS)

print.o: print.cpp
	$(CPP) -c print.cpp -o print.o $(CXXFLAGS)
